// <auto-generated />
using System;
using InventoryDemo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryDemo.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDemoDbContext))]
    [Migration("20230619194517_refresh database with record table only")]
    partial class refreshdatabasewithrecordtableonly
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InventoryDemo.Core.Entities.Record", b =>
                {
                    b.Property<int>("PO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PO"), 1L, 1);

                    b.Property<int>("LOTnumber")
                        .HasColumnType("int");

                    b.Property<string>("machineName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("modifytime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("operatorDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("operatorName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("orderNumber")
                        .HasColumnType("int");

                    b.Property<int>("productCode")
                        .HasColumnType("int");

                    b.HasKey("PO");

                    b.ToTable("Record");
                });
#pragma warning restore 612, 618
        }
    }
}
